spring:
  application:
    name: CandiFlow
  datasource:
    url: jdbc:postgresql://localhost:25500/candiflowdb
    username: postgres
    password: Password7!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

    security:
      user:
        name: admin
        password: admin

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      org.springframework.security: info

jwt:
  secret: une-cle-secrete-tres-longue-et-securisee-en-base64-32chars
  expiration: 86400000